apiVersion: v1
kind: Pod
metadata:
  name: victim-pod-egress
  namespace: kube-system
  labels:
    app: vulnerable-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vulnerable-11-netpol-egress-allow-all
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: vulnerable-app
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0