apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vuln-complex-03-admin-daemonset
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      hostNetwork: true
      containers:
      - name: agent
        image: agent:1.2.0
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock