apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: subtle-11-netpol-egress-allow-all-global
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0