apiVersion: v1
kind: Pod
metadata:
  name: subtle-20-root-with-priv-escalation
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: true