apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: subtle-10-netpol-ingress-default-allow
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0