apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subtle-36-deployment-scaler
  namespace: production
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch"]