apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-complex-02-root-no-limits-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-app
  template:
    metadata:
      labels:
        app: legacy-app
    spec:
      containers:
      - name: legacy-web
        image: nginx:latest
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "64Mi"