apiVersion: v1
kind: Pod
metadata:
  name: subtle-16-root-with-hostpath
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /logs
      name: varlog
  volumes:
  - name: varlog
    hostPath:
      path: /var/log