apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: subtle-10-netpol-ingress-allow-all-global
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0