apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subtle-40-cluster-admin-binding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: build-bot-sa
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io