apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-13-cpu-request-missing
spec:
  containers:
  - name: no-cpu-request
    image: busybox:1.36
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        memory: "64Mi"