apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-11-cpu-limit-missing
spec:
  containers:
  - name: cpu-eater
    image: busybox:1.36
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        memory: "128Mi"