apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-24-docker-sock
spec:
  containers:
  - name: dind
    image: docker:dind
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock