apiVersion: v1
kind: Pod
metadata:
  name: victim-pod-ingress
  namespace: kube-system
  labels:
    app: vulnerable-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vulnerable-10-netpol-ingress-allow-all
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: vulnerable-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0