apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-25-all-problems
  namespace: default
spec:
  hostPID: true
  hostNetwork: true
  hostIPC: true
  automountServiceAccountToken: true
  containers:
  - name: nightmare-container
    image: alpine:latest
    command: ["sleep", "3600"]
    ports:
    - containerPort: 80
      hostPort: 8000
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      runAsUser: 0
      readOnlyRootFilesystem: false
      capabilities:
        add: ["ALL"]
    resources: {}
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock