apiVersion: v1
kind: Service
metadata:
  name: subtle-13-service-nodeport
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
    nodePort: 30080