apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-complex-15-sa-token-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp:latest