apiVersion: v1
kind: Pod
metadata:
  name: subtle-17-hostnet-with-netraw
spec:
  hostNetwork: true
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]