apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-07-default-ns-pod
  namespace: default
spec:
  containers:
  - name: root-shell
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0