apiVersion: v1
kind: Pod
metadata:
  name: subtle-19-priv-with-dev-hostpath
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host-dev
      name: dev
  volumes:
  - name: dev
    hostPath:
      path: /dev