apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subtle-36-deployment-scaler-global
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["*"]