apiVersion: batch/v1
kind: CronJob
metadata:
  name: subtle-48-cronjob-concurrency-allow
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: busybox:1.36
          restartPolicy: OnFailure