apiVersion: v1
kind: Pod
metadata:
  name: subtle-30-netadmin-as-nonroot
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1001
      capabilities:
        add: ["NET_ADMIN"]