apiVersion: v1
kind: Pod
metadata:
  name: subtle-24-docker-sock-writable
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
      readOnly: false
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock