apiVersion: v1
kind: Pod
metadata:
  name: subtle-18-hostpid-with-ptrace
spec:
  hostPID: true
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]