apiVersion: v1
kind: Pod
metadata:
  name: subtle-43-liveness-touch
spec:
  containers:
  - name: main
    image: nginx:1.25.3
    livenessProbe:
      exec:
        command:
        - touch
        - /tmp/healthy
      initialDelaySeconds: 10