apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vuln-single-04-runasnonroot-false
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: database
        image: mysql:8.0
        securityContext:
          runAsNonRoot: true