apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: subtle-27-hostnet-daemonset
spec:
  selector:
    matchLabels:
      app: net-agent
  template:
    metadata:
      labels:
        app: net-agent
    spec:
      hostNetwork: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: main
        image: agent:1.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL