apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-22-sa-token-automount
spec:
  automountServiceAccountToken: false
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]