apiVersion: batch/v1
kind: CronJob
metadata:
  name: vuln-complex-05-insecure-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup-script
            image: alpine:3.18
            securityContext:
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
            resources:
              limits:
                pids: 2048