apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-05-hostpid
spec:
  hostPID: false
  containers:
  - name: process-snooper
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL