apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vuln-single-14-mem-request-missing
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: database
        image: mysql:8.0
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL