apiVersion: batch/v1
kind: CronJob
metadata:
  name: subtle-25-root-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
          containers:
          - name: main
            image: alpine:3.18
            securityContext:
              capabilities:
                drop:
                - ALL
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: OnFailure