apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vuln-complex-14-insecure-defaults
spec:
  serviceName: "app"
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: my-app:1.0.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000