apiVersion: batch/v1
kind: CronJob
metadata:
  name: subtle-25-root-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1001
          containers:
          - name: main
            image: alpine:3.18
          restartPolicy: OnFailure