apiVersion: v1
kind: Pod
metadata:
  name: subtle-06-caps-default
  namespace: default
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        drop: ["ALL"]
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534