apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subtle-26-statefulset-hostpath
spec:
  selector:
    matchLabels:
      app: my-db
  serviceName: "my-db-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: my-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: main
        image: mysql:8.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        emptyDir: {}