apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-25-all-problems
  namespace: production
spec:
  hostPID: false
  hostNetwork: false
  hostIPC: false
  automountServiceAccountToken: false
  containers:
  - name: nightmare-container
    image: alpine:3.18
    command: ["sleep", "3600"]
    ports:
    - containerPort: 80
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 1001
      readOnlyRootFilesystem: true
      capabilities: {}
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"