apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-25-add-capability
spec:
  containers:
  - name: net-admin-container
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault