apiVersion: v1
kind: Pod
metadata:
  name: subtle-05-seccomp-container-default
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault