apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-18-privileged-no-limits
spec:
  containers:
  - name: priv-no-limit
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      privileged: false
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"