apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-complex-24-root-escalate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: my-app:1.0.0
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault