apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-13-sys-admin
spec:
  containers:
  - name: sys-admin-pod
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1001
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false