apiVersion: v1
kind: Pod
metadata:
  name: subtle-04-seccomp-pod-default
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]