apiVersion: v1
kind: Pod
metadata:
  name: subtle-04-seccomp-pod-default
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      capabilities:
        drop:
        - ALL