apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vuln-complex-16-all-host-access
spec:
  selector:
    matchLabels:
      app: host-agent
  template:
    metadata:
      labels:
        app: host-agent
    spec:
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
      - name: agent
        image: agent:1.0