apiVersion: v1
kind: Pod
metadata:
  name: subtle-09-runasuser-default
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1001