apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-36-deployment-viewer
  namespace: production
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]