apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-complex-15-sa-token-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: myapp-container
        image: myapp:1.0.5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL