apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subtle-39-csr-approver
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get", "list", "watch"]