apiVersion: v1
kind: Pod
metadata:
  name: subtle-47-default-sa-usage
spec:
  serviceAccountName: my-app-sa
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL