apiVersion: v1
kind: Pod
metadata:
  name: subtle-43-liveness-touch
spec:
  containers:
  - name: main
    image: nginx:1.25.3
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10