apiVersion: v1
kind: Pod
metadata:
  name: subtle-12-apparmor-default
  annotations:
    container.apparmor.security.beta.kubernetes.io/main: runtime/default
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL