apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-03-runasuser-zero
spec:
  containers:
  - name: root-container
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL