apiVersion: v1
kind: Pod
metadata:
  name: subtle-44-qos-guaranteed-inflexible
spec:
  containers:
  - name: main
    image: nginx:1.25.3
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"