apiVersion: v1
kind: Pod
metadata:
  name: vuln-complex-22-kubelet
  namespace: kube-system
spec:
  containers:
  - name: kubelet
    image: k8s.gcr.io/kubelet:v1.25.3
    command:
    - kubelet
    - --anonymous-auth=false
    - --authorization-mode=Webhook