apiVersion: v1
kind: Pod
metadata:
  name: victim-pod-ingress
  namespace: kube-system
  labels:
    app: vulnerable-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-10-netpol-ingress-default-deny
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: vulnerable-app
  policyTypes:
  - Ingress