apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-single-08-hostport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-server
        image: nginx:1.25.3
        ports:
        - containerPort: 80