apiVersion: v1
kind: Pod
metadata:
  name: vuln-single-07-hostipc
spec:
  hostIPC: false
  containers:
  - name: ipc-listener
    image: busybox:1.36
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL