apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vuln-complex-17-pod-admin
  namespace: production
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]