apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vuln-single-17-rbac-resource-wildcard
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]